name: my-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: composer exec phpcs -- --standard=PSR12 src/ tests/
      - run: composer exec --verbose phpunit tests
